language: java
before_install:
- openssl aes-256-cbc -K $encrypted_6ff670030a11_key -iv $encrypted_6ff670030a11_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
