language: java
before_install:
- openssl aes-256-cbc -K $encrypted_b3880e1d291d_key -iv $encrypted_b3880e1d291d_iv
  -in src/main/resources/application.yml.enc -out src/main/resources/application.yml -d
